apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mh9h0m2st-go
  janus-idp.io/tekton: mh9h0m2st-go
  backstage.io/kubernetes-id: mh9h0m2st-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mh9h0m2st-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
