apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mh9h0m2st-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mh9h0m2st-go 
  name: mh9h0m2st-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mh9h0m2st-go 
